"""
Django settings for LibraryProject project.
Generated by 'django-admin startproject' using Django 5.2.7.
"""

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

# =====================================================
# BASIC SETTINGS
# =====================================================

SECRET_KEY = 'django-insecure-3m8jowr76y57bd$-3cxn&_bqx=ug3-2)e%7^bubq$e0jjs6)3_'

# ⚠️ For development keep this True
DEBUG = True  

ALLOWED_HOSTS = []


# =====================================================
# INSTALLED APPS
# =====================================================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Your apps
    'bookshelf',
    'relationship_app',
]


# =====================================================
# MIDDLEWARE
# =====================================================

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# =====================================================
# URLS & TEMPLATES
# =====================================================

ROOT_URLCONF = 'LibraryProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        # IMPORTANT: Correct templates directory
        'DIRS': [
            BASE_DIR / 'templates',
        ],

        'APP_DIRS': True,

        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'LibraryProject.wsgi.application'


# =====================================================
# DATABASE
# =====================================================

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# =====================================================
# PASSWORD VALIDATORS
# =====================================================

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# =====================================================
# INTERNATIONAL
# =====================================================

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# =====================================================
# STATIC & MEDIA
# =====================================================

STATIC_URL = '/static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# =====================================================
# CUSTOM USER MODEL
# =====================================================

AUTH_USER_MODEL = 'bookshelf.CustomUser'


# =====================================================
# SECURITY SETTINGS 
# (Safe for development)
# =====================================================

# Do NOT use secure cookies on localhost
CSRF_COOKIE_SECURE = False
SESSION_COOKIE_SECURE = False

SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# =====================================================
# SECURITY SETTINGS
# =====================================================

# ⚠️ Development vs Production toggle
import os
IS_PROD = os.getenv('DJANGO_ENV') == 'production'

DEBUG = not IS_PROD
ALLOWED_HOSTS = ['yourdomain.com', 'www.yourdomain.com'] if IS_PROD else []

# --- HTTPS enforcement ---
SECURE_SSL_REDIRECT = IS_PROD  # Redirect all HTTP to HTTPS

# --- HSTS (strict HTTPS policy) ---
SECURE_HSTS_SECONDS = 31536000 if IS_PROD else 0  # 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = IS_PROD
SECURE_HSTS_PRELOAD = IS_PROD

# --- Secure cookies ---
SESSION_COOKIE_SECURE = IS_PROD
CSRF_COOKIE_SECURE = IS_PROD

# --- Browser-side protections ---
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# --- Proxy awareness (important if behind Nginx/Apache/Heroku/etc.) ---
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
